### PR TITLE
Add logo assets to /assets

### PR DESCRIPTION
**Pull request by jakelang**

### CODE REVIEW

**Comment by axic** [comment]
Also need to add rendered versions and removing obsolete ones.

**Comment by axic** [comment]
> LGTMl; I can't merge

Merging this would mean there are like 6 conflicting versions of the logo in the repo. Also all the rendered version in the repo would be different from this one.

**Comment by jakelang** [comment]
@hugo-dc @lrettig can one of you do the renders and just push over this branch?

**Comment by jakelang** [comment]
Also, rebased @axic

**Comment by hugo-dc** [comment]
I'm not sure which other vector formats besides svg can be used on a linux computer

**Comment by axic** [comment]
Either please replace the SVG with the same version as the other files or remove the SVG in this PR.

Have two conflicting versions would be confusing in the future.

**Comment by lrettig** [comment]
I think this is the latest SVG: https://drive.google.com/open?id=1hzfuPdoFVKPlcnFl8Rls6IYWggHG-8g0

**Comment by jakelang** [comment]
@axic @lrettig updated with the latest svg.

**Comment by jakelang** [comment]
@axic @lrettig any reason this cannot be merged yet?

**Comment by lrettig** [comment]
LGTM. I don't have merge access.

**Comment by axic** [comment]
> Merging this would mean there are like 6 conflicting versions of the logo in the repo. Also all the rendered version in the repo would be different from this one.

Ah, it seems the renders are still not updated, all the `.jpg` files.

**Comment by axic** [comment]
Created an issue to track that: #171.

**Pull request merged**
